// const WORD_SETS_FIRST = [
//   {
//     words: ["ash", "future"],
//     hint: "Universe",
//     model: "bert_nn",
//   },
//   {
//     words: ["water", "salad"],
//     hint: "Soup",
//     model: "bert_nn",
//   },
//   {
//     words: ["planets", "neptune"],
//     hint: "Jupiter",
//     model: "bert_nn",
//   },
//   {
//     words: ["hot", "wheel"],
//     hint: "Intense",
//     model: "bert_nn",
//   },
//   {
//     words: ["cannon", "genius"],
//     hint: "Guns",
//     model: "glove_nn",
//   },
//   {
//     words: ["magazine", "duel"],
//     hint: "Editor",
//     model: "glove_nn",
//   },
//   {
//     words: ["farm", "potato"],
//     hint: "Agricultural",
//     model: "glove_nn",
//   },
//   {
//     words: ["small", "rage"],
//     hint: "Large",
//     model: "glove_nn",
//   },
//   {
//     words: ["king", "clown"],
//     hint: "Queen",
//     model: "bert",
//   },
//   {
//     words: ["diamond", "junk"],
//     hint: "Spaghetti",
//     model: "bert",
//   },
//   {
//     words: ["philippine", "vegas"],
//     hint: "Luzon",
//     model: "bert",
//   },
//   { words: ["cane", "turn"], hint: "Drive", model: "bert" },
//   {
//     words: ["frankenstein", "application"],
//     hint: "Dracula",
//     model: "glove",
//   },
//   {
//     words: ["figure", "post"],
//     hint: "Office",
//     model: "glove",
//   },
//   {
//     words: ["dress", "cinderella"],
//     hint: "Attire",
//     model: "glove",
//   },
//   {
//     words: ["sun", "solar"],
//     hint: "Photovoltaic",
//     model: "glove",
//   },
//   {
//     words: ["ocean", "sea"],
//     hint: "Underwater",
//     model: "bert_nn",
//   },
//   {
//     words: ["mountain", "peak"],
//     hint: "Slopes",
//     model: "glove_nn",
//   },
//   {
//     words: ["computer", "processor"],
//     hint: "Laptop",
//     model: "bert",
//   },
//   {
//     words: ["artist", "painting"],
//     hint: "Sculpture",
//     model: "glove",
//   },
// ];

// const RANDOM_WORDS_FIRST = {
//   1: [
//     "LETTER",
//     "SHAMPOO",
//     "GERMANY",
//     "TEMPLE",
//     "FLAT",
//     "AXE",
//     "PIANO",
//     "BAT",
//     "SOAP",
//     "SCRATCH",
//     "TORCH",
//     "STRING",
//     "VET",
//     "SADDLE",
//     "TABLE",
//     "MISSIONARY",
//     "HEAD",
//     "WILD",
//     "BERMUDA",
//     "GLASSES",
//     "WAKE",
//     "COTTON",
//     "FILE",
//   ],
//   2: [
//     "BARBECUE",
//     "FOG",
//     "AMBULANCE",
//     "STRIKE",
//     "CAMP",
//     "NEWTON",
//     "UNIVERSITY",
//     "ROBOT",
//     "SCRATCH",
//     "CABLE",
//     "SHELL",
//     "TIE",
//     "CHEESE",
//     "KANGAROO",
//     "MOON",
//     "PIZZA",
//     "SWALLOW",
//     "BEER",
//     "TASTE",
//     "LAUNDRY",
//     "STEEL",
//     "STRING",
//     "TUBE",
//   ],
//   3: [
//     "CONFUCIUS",
//     "PRISON",
//     "CHEVRON",
//     "BEVERAGE",
//     "AUTHOR",
//     "ROE",
//     "BUFFET",
//     "BLOOD",
//     "SHERLOCK",
//     "FIT",
//     "GANG",
//     "CREATURE",
//     "BIRTH",
//     "FURNITURE",
//     "EMERALD",
//     "FIREPLACE",
//     "TIN",
//     "MAZE",
//     "EXPANSION",
//     "DISCORD",
//     "CLOWN",
//     "ASTRONOMY",
//     "BRUSH",
//   ],
//   4: [
//     "CRANK",
//     "DECEMBER",
//     "PINK",
//     "OYSTER",
//     "MISSIONARY",
//     "SQUASH",
//     "VIRUS",
//     "ELEPHANT",
//     "FANG",
//     "GENIE",
//     "BUST",
//     "BICYCLE",
//     "SCREW",
//     "MARATHON",
//     "SHEPHERD",
//     "ALCHEMIST",
//     "SCARECROW",
//     "PAINT",
//     "CHEEK",
//     "POWDER",
//     "ROOF",
//     "CAT",
//     "SQUARE",
//   ],
//   5: [
//     "GOAT",
//     "CROW",
//     "WATER",
//     "HIMALAYAS",
//     "ASTRONAUT",
//     "PIPE",
//     "PIRATE",
//     "UNIVERSITY",
//     "SHAMPOO",
//     "MOHAWK",
//     "HEART",
//     "SNOWFLAKE",
//     "STADIUM",
//     "GAME",
//     "CAESAR",
//     "EASTER",
//     "SPHINX",
//     "WINDOW",
//     "MANICURE",
//     "FOOT",
//     "ANCHOR",
//     "SQUARE",
//     "HORN",
//   ],
//   6: [
//     "DECK",
//     "PEACH",
//     "KING",
//     "PISTOL",
//     "LION",
//     "AFRICA",
//     "KNIFE",
//     "PRINCESS",
//     "CAP",
//     "LIFE",
//     "ICE",
//     "BILL",
//     "MASS",
//     "CUCUMBER",
//     "CYCLE",
//     "JUPITER",
//     "SOLAR",
//     "DISEASE",
//     "CRASH",
//     "FALL",
//     "EYE",
//     "SHAKESPEARE",
//     "BELT",
//   ],
//   7: [
//     "SPIDER",
//     "JEWEL",
//     "BEAN",
//     "EDEN",
//     "WEDDING",
//     "WEB",
//     "FEVER",
//     "WAITRESS",
//     "SUGAR",
//     "ROAD",
//     "SHADOW",
//     "PAGE",
//     "TORCH",
//     "THUMB",
//     "UNDERTAKER",
//     "SHERWOOD",
//     "GOAT",
//     "VAN",
//     "RULER",
//     "SHOULDER",
//     "BOXER",
//     "TAG",
//     "AZTEC",
//   ],
//   8: [
//     "LUCK",
//     "BEER",
//     "MOSES",
//     "NINJA",
//     "BASKETBALL",
//     "BRAZIL",
//     "JUDGE",
//     "BERLIN",
//     "TRAIN",
//     "SPRING",
//     "FALL",
//     "BACK",
//     "TEACHER",
//     "TRUNK",
//     "KING",
//     "LITTER",
//     "EINSTEIN",
//     "JET",
//     "BRIDE",
//     "IRON",
//     "IVORY",
//     "FARM",
//     "FILE",
//   ],
//   9: [
//     "BRICK",
//     "CABIN",
//     "JELLYFISH",
//     "SILVER",
//     "ALERT",
//     "CENTURY",
//     "QUILL",
//     "BEARD",
//     "CASTLE",
//     "EARTH",
//     "CARGO",
//     "MEDIC",
//     "CLOCK",
//     "FANG",
//     "SALT",
//     "SLAY",
//     "AUTHOR",
//     "DIARY",
//     "POTATO",
//     "ALWAYS",
//     "SABOTAGE",
//     "MUSKETEER",
//     "MOUNTIE",
//   ],
//   10: [
//     "CARD",
//     "CHERRY",
//     "BERMUDA",
//     "CIRCLE",
//     "BALL",
//     "BRUSH",
//     "MUMMY",
//     "THIEF",
//     "THUMB",
//     "UNDERTAKER",
//     "BRIDGE",
//     "CHURCH",
//     "NURSE",
//     "BEAT",
//     "SKUNK",
//     "JOCKEY",
//     "BOLT",
//     "BACK",
//     "COMPOUND",
//     "COMIC",
//     "CHECK",
//     "VENUS",
//     "FEVER",
//   ],
//   11: [
//     "SPRING",
//     "KNEE",
//     "HAM",
//     "SATELLITE",
//     "TURTLE",
//     "WISH",
//     "POLE",
//     "SCALE",
//     "TELESCOPE",
//     "TEACHER",
//     "OIL",
//     "SALAD",
//     "WAKE",
//     "NUT",
//     "ATLANTIS",
//     "TIP",
//     "TAIL",
//     "NAIL",
//     "BEE",
//     "DAY",
//     "BISCUIT",
//     "PAD",
//     "FIRE",
//   ],
//   12: [
//     "LIMOUSINE",
//     "KID",
//     "LEMON",
//     "POWDER",
//     "CAMEL",
//     "MAIL",
//     "KING",
//     "TENT",
//     "WINE",
//     "SHERWOOD",
//     "TABOO",
//     "WET",
//     "INDIA",
//     "VEIN",
//     "MARCH",
//     "IRON",
//     "BICYCLE",
//     "SOLO",
//     "HOT",
//     "LOCK",
//     "LOCH NESS",
//     "PEA",
//     "JUPITER",
//   ],
//   13: [
//     "BANANA",
//     "DEATH",
//     "SUN",
//     "PADDLE",
//     "COLD",
//     "AMAZON",
//     "DRAG",
//     "FRANCE",
//     "SUIT",
//     "DICE",
//     "CAMP",
//     "TAG",
//     "CONCERT",
//     "BATH",
//     "BUTTERFLY",
//     "BLACKSMITH",
//     "WAR",
//     "CAPITAL",
//     "PENTAGON",
//     "BOTTLE",
//     "EGYPT",
//     "STAMP",
//     "ANGEL",
//   ],
//   14: [
//     "MICROSCOPE",
//     "MOSCOW",
//     "LASER",
//     "TURN",
//     "COLUMBUS",
//     "BEAM",
//     "SPOT",
//     "DEGREE",
//     "BOMB",
//     "POISON",
//     "DOLLAR",
//     "MINE",
//     "PLOT",
//     "SCORPION",
//     "SHOP",
//     "PUMPKIN",
//     "JET",
//     "JAM",
//     "NAVAL",
//     "CANE",
//     "HORSE",
//     "OIL",
//     "NURSE",
//   ],
//   15: [
//     "GIRL",
//     "MODE",
//     "ROOKIE",
//     "CALENDAR",
//     "SWEAT",
//     "LACE",
//     "SHARE",
//     "ONION",
//     "CLOUD",
//     "MONKEY",
//     "SALT",
//     "STAG",
//     "ARTIST",
//     "PAINTING",
//     "FANG",
//     "STONEHENGE",
//     "ICE",
//     "POLE",
//     "PINK",
//     "SPINE",
//     "DRIVER",
//     "PILLOW",
//     "MUSKETEER",
//   ],
//   16: [
//     "BERLIN",
//     "KNIFE",
//     "SHOP",
//     "ATLANTIS",
//     "ROOT",
//     "EGYPT",
//     "FANG",
//     "IVORY",
//     "BELL",
//     "BOX",
//     "POUND",
//     "PISTOL",
//     "MASS",
//     "PLASTIC",
//     "PEPPER",
//     "HOLLYWOOD",
//     "CHEST",
//     "SCORPION",
//     "FIDDLE",
//     "BOOT",
//     "IRON",
//     "EYE",
//     "OLIVE",
//   ],
//   17: [
//     "COMPUTER",
//     "ARM",
//     "SQUARE",
//     "SHED",
//     "STAR",
//     "SPOT",
//     "PROCESSOR",
//     "ANGEL",
//     "CYCLE",
//     "BEIJING",
//     "PILOT",
//     "AUSTRALIA",
//     "SHOT",
//     "ROW",
//     "FALL",
//     "SKI",
//     "AIR",
//     "FISH",
//     "BAR",
//     "PIRATE",
//     "SERVER",
//     "DUCK",
//     "SKYSCRAPER",
//   ],
//   18: [
//     "MATTRESS",
//     "LOOSE",
//     "SAFE",
//     "RAGE",
//     "FARM",
//     "STEAM",
//     "CRICKET",
//     "RED",
//     "PILOT",
//     "GENIE",
//     "HEART",
//     "HERCULES",
//     "COUNTRY",
//     "COVER",
//     "DELTA",
//     "REVOLUTION",
//     "BOTTOM",
//     "FLUFF",
//     "MEXICO",
//     "BLACK",
//     "IVORY",
//     "WILD",
//     "ANIMAL",
//   ],
//   19: [
//     "APPLE",
//     "OLYMPUS",
//     "STRAW",
//     "SOUL",
//     "MIRROR",
//     "CRYSTAL",
//     "GREECE",
//     "MARACAS",
//     "EMBASSY",
//     "STAR",
//     "CRAB",
//     "STEAM",
//     "AZTEC",
//     "VEGAS",
//     "TRICK",
//     "WATER",
//     "AXE",
//     "KEY",
//     "BUCK",
//     "LAWYER",
//     "BOXER",
//     "PENGUIN",
//     "ROBOT",
//   ],
//   20: [
//     "DRESS",
//     "KNOB",
//     "THROAT",
//     "FLUFF",
//     "BETA",
//     "GANG",
//     "GROUP",
//     "EAT",
//     "MOTEL",
//     "GRANDMA",
//     "CINDERELLA",
//     "CHEEK",
//     "RACK",
//     "SHIPYARD",
//     "PRICK",
//     "BREAK",
//     "BOMB",
//     "BONSAI",
//     "EMISSION",
//     "CANDLE",
//     "SWEAT",
//     "LOTION",
//     "DRONE",
//   ],
// };

// Second test

// 2 words
// const WORD_SETS_2 = [
//   {
//     words: ["MIRROR", "FURNACE"],
//     hint: "doorway",
//     model: "bert_nn",
//   },
//   {
//     words: ["TORNADO", "COMPASS"],
//     hint: "landslide",
//     model: "bert_nn",
//   },
//   {
//     words: ["PRINCE", "CROSSBOW"],
//     hint: "bodyguards",
//     model: "bert_nn",
//   },
//   {
//     words: ["ANDROID", "CLOCK"],
//     hint: "rack",
//     model: "bert_nn",
//   },
//   {
//     words: ["DRAGON", "MOON"],
//     hint: "shadow",
//     model: "bert_nn",
//   },
//   {
//     words: ["BUBBLE", "TSUNAMI"],
//     hint: "earthquake",
//     model: "glove",
//   },
//   {
//     words: ["MOUNTAIN", "FROG"],
//     hint: "toad",
//     model: "glove",
//   },
//   {
//     words: ["SPIDER", "SHARK"],
//     hint: "whale",
//     model: "glove",
//   },
//   {
//     words: ["ASTEROID", "EARTH"],
//     hint: "planet",
//     model: "glove",
//   },
//   {
//     words: ["PIXEL", "WAVE"],
//     hint: "tidal",
//     model: "glove",
//   },
// ];

// const RANDOM_WORDS_2 = {
//   1: [
//     "LADDER",
//     "TIGER",
//     "PENCIL",
//     "WHEEL",
//     "CLOUD",
//     "MAP",
//     "RANDOM",
//     "TUNNEL",
//     "BREAD",
//     "WAVE",
//     "SPIDER",
//     "JOURNAL",
//     "CAVE",
//     "BUTTON",
//     "SUN",
//     "PLASTIC",
//     "CROWN",
//     "HORN",
//     "CHECK",
//     "PLANET",
//     "GUITAR",
//     "HOLE",
//     "BELL",
//   ],
//   2: [
//     "APPLE",
//     "MOON",
//     "TOWER",
//     "VIOLIN",
//     "OCTOPUS",
//     "SUBMARINE",
//     "ECHO",
//     "PIXEL",
//     "STONE",
//     "FORK",
//     "BUG",
//     "LADDER",
//     "LAMP",
//     "BACKPACK",
//     "BICYCLE",
//     "ROVER",
//     "ASTEROID",
//     "FEATHER",
//     "MOUSE",
//     "DUST",
//     "UMBRELLA",
//     "CANDLE",
//     "NOTEBOOK",
//   ],
//   3: [
//     "ELEPHANT",
//     "BALLOON",
//     "RING",
//     "VIOLET",
//     "GOBLIN",
//     "SCREEN",
//     "DUNGEON",
//     "BATTERY",
//     "SNAKE",
//     "CIRCUIT",
//     "TIGER",
//     "DIVER",
//     "JOURNAL",
//     "CAVE",
//     "LANCE",
//     "WIRE",
//     "OCEAN",
//     "ZOMBIE",
//     "SATELLITE",
//     "HOLE",
//     "MIRROR",
//     "BOTTLE",
//     "BACKPACK",
//   ],
//   4: [
//     "FROG",
//     "PIRATE",
//     "BLACKHOLE",
//     "CHESS",
//     "FIRE",
//     "SUNSET",
//     "TREE",
//     "GUITAR",
//     "DEER",
//     "MATRIX",
//     "PENCIL",
//     "FOX",
//     "ROBOT",
//     "BROOM",
//     "LAGOON",
//     "HACKER",
//     "PLANE",
//     "CROWN",
//     "SHIP",
//     "WATERFALL",
//     "SILK",
//     "BREAD",
//     "MOUSE",
//   ],
//   5: [
//     "SPACESHIP",
//     "ISLAND",
//     "CASTLE",
//     "MOAT",
//     "BICYCLE",
//     "TIGER",
//     "PRINCESS",
//     "INTERNET",
//     "PROGRAM",
//     "BUG",
//     "GHOST",
//     "ROCKET",
//     "JUPITER",
//     "CARROT",
//     "MOUNTAIN",
//     "WOOD",
//     "CANDLE",
//     "SCREEN",
//     "PEARL",
//     "TORCH",
//     "FURNACE",
//     "LADDER",
//     "CREEK",
//   ],
//   6: [
//     "JUNGLE",
//     "RAIN",
//     "CLOUD",
//     "TREE",
//     "BUTTON",
//     "PLANET",
//     "MUSIC",
//     "TOWER",
//     "GOBLIN",
//     "DIVER",
//     "WINDOW",
//     "LAGOON",
//     "OYSTER",
//     "PRINCE",
//     "FIRE",
//     "POTION",
//     "SATELLITE",
//     "CANDLE",
//     "FOSSIL",
//     "TIGER",
//     "SUN",
//     "BALLOON",
//     "TORCH",
//   ],
//   7: [
//     "GUITAR",
//     "BRIDGE",
//     "POTION",
//     "JOURNAL",
//     "NEBULA",
//     "TUNNEL",
//     "SPIDER",
//     "PIRATE",
//     "CAVE",
//     "BATTERY",
//     "CREEK",
//     "CASTLE",
//     "SUBMARINE",
//     "FURNACE",
//     "VIRUS",
//     "PLUTO",
//     "FIRE",
//     "CANDLE",
//     "OAK",
//     "VALLEY",
//     "EAGLE",
//     "TOWER",
//     "NOTEBOOK",
//   ],
//   8: [
//     "ROVER",
//     "CUP",
//     "LADDER",
//     "MOUNTAIN",
//     "VAMPIRE",
//     "CHIP",
//     "PIRATE",
//     "BUG",
//     "HORSE",
//     "CASTLE",
//     "SHIELD",
//     "CAVE",
//     "DIVER",
//     "SUN",
//     "WHEEL",
//     "TORNADO",
//     "BOTTLE",
//     "MIRROR",
//     "PLASTIC",
//     "SAND",
//     "CARROT",
//     "GOBLIN",
//     "PLANET",
//   ],
//   9: [
//     "OCTOPUS",
//     "SPACESHIP",
//     "SATELLITE",
//     "GHOST",
//     "BLACKHOLE",
//     "FEATHER",
//     "WATER",
//     "RIVER",
//     "MAP",
//     "CLOUD",
//     "SILK",
//     "CARROT",
//     "LAGOON",
//     "LAMP",
//     "OYSTER",
//     "WHALE",
//     "DUNGEON",
//     "ISLAND",
//     "BICYCLE",
//     "TUNNEL",
//     "SCREEN",
//     "FIRE",
//     "DUST",
//   ],
//   10: [
//     "ROBOT",
//     "NEBULA",
//     "CANDLE",
//     "VIOLIN",
//     "MATRIX",
//     "JOURNAL",
//     "SERVER",
//     "ASTRONAUT",
//     "GOBLIN",
//     "VILLAGE",
//     "CASTLE",
//     "TORNADO",
//     "POTION",
//     "PAPER",
//     "CREEK",
//     "RAIN",
//     "SUBMARINE",
//     "FURNACE",
//     "SCREEN",
//     "GUITAR",
//     "CROSSBOW",
//     "DRONE",
//     "MIRROR",
//   ],
// };

//3 words

const WORD_SETS = [
  {
    words: ["BUTTON", "HOLE", "PLANET"],
    hint: "box",
    model: "bert_nn",
  },
  {
    words: ["BICYCLE", "FEATHER", "DUST"],
    hint: "helmets",
    model: "bert_nn",
  },
  {
    words: ["WIRE", "SATELLITE", "BOTTLE"],
    hint: "radar",
    model: "bert_nn",
  },
  {
    words: ["MOUSE", "SILK", "ANDROID"],
    hint: "rabbit",
    model: "bert_nn",
  },
  {
    words: ["GHOST", "CANDLE", "LADDER"],
    hint: "neon",
    model: "bert_nn",
  },
  {
    words: ["OYSTER", "FOSSIL", "TORCH"],
    hint: "flame",
    model: "glove",
  },
  {
    words: ["SPIDER", "VALLEY", "EAGLE"],
    hint: "river",
    model: "glove",
  },
  {
    words: ["CASTLE", "CAVE", "SUN"],
    hint: "manor",
    model: "glove",
  },
  {
    words: ["LAGOON", "OYSTER", "Dungeon"],
    hint: "clam",
    model: "glove",
  },
  {
    words: ["SERVER", "TORNADO", "Potion"],
    hint: "desktop",
    model: "glove",
  },
];

const RANDOM_WORDS = {
  1: [
    "LADDER",
    "TIGER",
    "PENCIL",
    "WHEEL",
    "CLOUD",
    "MAP",
    "RANDOM",
    "TUNNEL",
    "BREAD",
    "WAVE",
    "SPIDER",
    "JOURNAL",
    "CAVE",
    "SUN",
    "PLASTIC",
    "CROWN",
    "HORN",
    "CHECK",
    "GUITAR",
    "BELL",
    "BUFFALO",
    "VIOLIN",
  ],
  2: [
    "APPLE",
    "MOON",
    "TOWER",
    "VIOLIN",
    "OCTOPUS",
    "SUBMARINE",
    "ECHO",
    "PIXEL",
    "STONE",
    "FORK",
    "BUG",
    "LADDER",
    "LAMP",
    "BACKPACK",
    "ROVER",
    "ASTEROID",
    "MOUSE",
    "UMBRELLA",
    "CANDLE",
    "NOTEBOOK",
    "TORNADO",
    "COMPASS",
  ],
  3: [
    "ELEPHANT",
    "BALLOON",
    "RING",
    "VIOLET",
    "GOBLIN",
    "SCREEN",
    "DUNGEON",
    "BATTERY",
    "SNAKE",
    "CIRCUIT",
    "TIGER",
    "DIVER",
    "JOURNAL",
    "CAVE",
    "LANCE",
    "OCEAN",
    "ZOMBIE",
    "HOLE",
    "MIRROR",
    "BACKPACK",
    "PRINCE",
    "CROSSBOW",
  ],
  4: [
    "FROG",
    "PIRATE",
    "BLACKHOLE",
    "CHESS",
    "FIRE",
    "SUNSET",
    "TREE",
    "GUITAR",
    "DEER",
    "MATRIX",
    "PENCIL",
    "FOX",
    "ROBOT",
    "BROOM",
    "LAGOON",
    "HACKER",
    "PLANE",
    "CROWN",
    "SHIP",
    "WATERFALL",
    "BREAD",
    "CLOCK",
  ],
  5: [
    "SPACESHIP",
    "ISLAND",
    "CASTLE",
    "MOAT",
    "BICYCLE",
    "TIGER",
    "PRINCESS",
    "INTERNET",
    "PROGRAM",
    "BUG",
    "ROCKET",
    "JUPITER",
    "CARROT",
    "MOUNTAIN",
    "WOOD",
    "SCREEN",
    "PEARL",
    "TORCH",
    "FURNACE",
    "CREEK",
    "DRAGON",
    "SILK",
  ],
  6: [
    "JUNGLE",
    "RAIN",
    "CLOUD",
    "TREE",
    "BUTTON",
    "PLANET",
    "MUSIC",
    "TOWER",
    "GOBLIN",
    "DIVER",
    "WINDOW",
    "LAGOON",
    "PRINCE",
    "FIRE",
    "POTION",
    "SATELLITE",
    "CANDLE",
    "TIGER",
    "SUN",
    "BALLOON",
    "BUBBLE",
    "TSUNAMI",
  ],
  7: [
    "GUITAR",
    "BRIDGE",
    "POTION",
    "JOURNAL",
    "NEBULA",
    "TUNNEL",
    "PIRATE",
    "BATTERY",
    "CREEK",
    "CASTLE",
    "SUBMARINE",
    "FURNACE",
    "VIRUS",
    "PLUTO",
    "FIRE",
    "CANDLE",
    "OAK",
    "TOWER",
    "NOTEBOOK",
    "CAVE",
    "ALONE",
    "BEST",
  ],
  8: [
    "ROVER",
    "CUP",
    "LADDER",
    "MOUNTAIN",
    "VAMPIRE",
    "CHIP",
    "PIRATE",
    "BUG",
    "HORSE",
    "SHIELD",
    "DIVER",
    "WHEEL",
    "TORNADO",
    "BOTTLE",
    "MIRROR",
    "PLASTIC",
    "SAND",
    "CARROT",
    "GOBLIN",
    "PLANET",
    "SHARK",
    "SPIDER",
  ],
  9: [
    "OCTOPUS",
    "SPACESHIP",
    "SATELLITE",
    "GHOST",
    "BLACKHOLE",
    "FEATHER",
    "WATER",
    "RIVER",
    "MAP",
    "CLOUD",
    "SILK",
    "CARROT",
    "LAMP",
    "WHALE",
    "ISLAND",
    "BICYCLE",
    "TUNNEL",
    "SCREEN",
    "FIRE",
    "DUST",
    "ASTEROID",
    "MOON",
  ],
  10: [
    "ROBOT",
    "NEBULA",
    "CANDLE",
    "VIOLIN",
    "MATRIX",
    "JOURNAL",
    "ASTRONAUT",
    "GOBLIN",
    "VILLAGE",
    "CASTLE",
    "PAPER",
    "CREEK",
    "RAIN",
    "SUBMARINE",
    "FURNACE",
    "SCREEN",
    "GUITAR",
    "CROSSBOW",
    "DRONE",
    "MIRROR",
    "PIXEL",
    "WAVE",
  ],
};

export { WORD_SETS, RANDOM_WORDS };
