const WORD_SETS = [
  {
    words: ["ash", "future"],
    hints: ["Universe", "Immortality", "Possible", "Possible"],
  },
  {
    words: ["water", "salad"],
    hints: ["Soup", "Soup", "Pasta", "Pasta"],
  },
  {
    words: ["planets", "neptune"],
    hints: ["Jupiter", "Jupiter", "Moons", "Moons"],
  },
  {
    words: ["hot", "wheel"],
    hints: ["Intense", "Intense", "Brakes", "Brakes"],
  },
  {
    words: ["cannon", "genius"],
    hints: ["Furnace", "Kite", "Guns", "Guns"],
  },
  {
    words: ["magazine", "duel"],
    hints: ["Rival", "Rival", "Editor", "Editor"],
  },
  {
    words: ["farm", "potato"],
    hints: ["Butcher", "Butcher", "Agricultural", "Agricultural"],
  },
  {
    words: ["small", "rage"],
    hints: ["Frustration", "Frustration", "Large", "Large"],
  },
  {
    words: ["king", "clown"],
    hints: ["Queen", "Queen", "Queen", "Queen"],
  },
  {
    words: ["diamond", "junk"],
    hints: ["Spaghetti", "Spaghetti", "Gold", "Gold"],
  },
  {
    words: ["philippine", "vegas"],
    hints: ["Luzon", "Luzon", "Las", "Las"],
  },
  { words: ["cane", "turn"], hints: ["Drive", "Drive", "Take", "Take"] },
  {
    words: ["frankenstein", "application"],
    hints: ["Superhero", "Superhero", "Dracula", "Dracula"],
  },
  {
    words: ["figure", "post"],
    hints: ["Fortress", "Stump", "Office", "Office"],
  },
  {
    words: ["dress", "cinderella"],
    hints: ["Doll", "Doll", "Attire", "Attire"],
  },
  {
    words: ["sun", "solar"],
    hints: ["Dome", "Dome", "Photovoltaic", "Photovoltaic"],
  },
  {
    words: ["ocean", "sea"],
    hints: ["Underwater", "Underwater", "Waters", "Waters"],
  },
  {
    words: ["mountain", "peak"],
    hints: ["Volcano", "Volcano", "Slopes", "Slopes"],
  },
  {
    words: ["computer", "processor"],
    hints: ["Laptop", "Laptop", "Software", "Software"],
  },
  {
    words: ["artist", "painting"],
    hints: ["Designer", "Designer", "Sculpture", "Sculpture"],
  },
];

const RANDOM_WORDS = {
  1: [
    "LETTER",
    "SHAMPOO",
    "GERMANY",
    "TEMPLE",
    "FLAT",
    "AXE",
    "PIANO",
    "BAT",
    "SOAP",
    "SCRATCH",
    "TORCH",
    "STRING",
    "VET",
    "SADDLE",
    "TABLE",
    "MISSIONARY",
    "HEAD",
    "WILD",
    "BERMUDA",
    "GLASSES",
    "WAKE",
    "COTTON",
    "FILE",
  ],
  2: [
    "BARBECUE",
    "FOG",
    "AMBULANCE",
    "STRIKE",
    "CAMP",
    "NEWTON",
    "UNIVERSITY",
    "ROBOT",
    "SCRATCH",
    "CABLE",
    "SHELL",
    "TIE",
    "CHEESE",
    "KANGAROO",
    "MOON",
    "PIZZA",
    "SWALLOW",
    "BEER",
    "TASTE",
    "LAUNDRY",
    "STEEL",
    "STRING",
    "TUBE",
  ],
  3: [
    "CONFUCIUS",
    "PRISON",
    "CHEVRON",
    "BEVERAGE",
    "AUTHOR",
    "ROE",
    "BUFFET",
    "BLOOD",
    "SHERLOCK",
    "FIT",
    "GANG",
    "CREATURE",
    "BIRTH",
    "FURNITURE",
    "EMERALD",
    "FIREPLACE",
    "TIN",
    "MAZE",
    "EXPANSION",
    "DISCORD",
    "CLOWN",
    "ASTRONOMY",
  ],
  4: [
    "CRANK",
    "DECEMBER",
    "PINK",
    "OYSTER",
    "MISSIONARY",
    "SQUASH",
    "VIRUS",
    "ELEPHANT",
    "FANG",
    "GENIE",
    "BUST",
    "BICYCLE",
    "SCREW",
    "MARATHON",
    "SHEPHERD",
    "ALCHEMIST",
    "SCARECROW",
    "PAINT",
    "CHEEK",
    "POWDER",
    "ROOF",
  ],
  5: [
    "GOAT",
    "CROW",
    "WATER",
    "HIMALAYAS",
    "ASTRONAUT",
    "PIPE",
    "PIRATE",
    "UNIVERSITY",
    "SHAMPOO",
    "MOHAWK",
    "HEART",
    "SNOWFLAKE",
    "STADIUM",
    "GAME",
    "CAESAR",
    "CANNON",
    "EASTER",
    "SPHINX",
    "GENIUS",
    "WINDOW",
    "MANICURE",
    "FOOT",
    "ANCHOR",
    "SQUARE",
    "HORN",
  ],
  6: [
    "DECK",
    "PEACH",
    "KING",
    "PISTOL",
    "LION",
    "AFRICA",
    "KNIFE",
    "PRINCESS",
    "CAP",
    "LIFE",
    "ICE",
    "BILL",
    "MASS",
    "CUCUMBER",
    "CYCLE",
    "JUPITER",
    "SOLAR",
    "DISEASE",
    "CRASH",
    "FALL",
    "EYE",
    "SHAKESPEARE",
    "AZTEC",
    "BELT",
  ],
  7: [
    "SPIDER",
    "JEWEL",
    "BEAN",
    "EDEN",
    "WEDDING",
    "WEB",
    "FEVER",
    "WAITRESS",
    "SUGAR",
    "ROAD",
    "SHADOW",
    "PAGE",
    "TORCH",
    "THUMB",
    "UNDERTAKER",
    "SHERWOOD",
    "GOAT",
    "VAN",
    "RULER",
    "SHOULDER",
    "BOXER",
    "TAG",
  ],
  8: [
    "LUCK",
    "BEER",
    "MOSES",
    "NINJA",
    "BASKETBALL",
    "BRAZIL",
    "JUDGE",
    "BERLIN",
    "MOON",
    "TRAIN",
    "SPRING",
    "FALL",
    "BACK",
    "TEACHER",
    "TRUNK",
    "KING",
    "LITTER",
    "EINSTEIN",
    "JET",
    "BRIDE",
    "IRON",
    "IVORY",
    "FARM",
    "FILE",
  ],
  9: [
    "BOSS",
    "BRICK",
    "CABIN",
    "JELLYFISH",
    "SILVER",
    "ALERT",
    "CENTURY",
    "QUILL",
    "BEARD",
    "CASTLE",
    "EARTH",
    "CARGO",
    "MEDIC",
    "CLOCK",
    "FANG",
    "SALT",
    "SLAY",
    "AUTHOR",
    "DIARY",
    "POTATO",
    "ALWAYS",
    "SABOTAGE",
    "MUSKETEER",
    "MOUNTIE",
  ],
  10: [
    "CARD",
    "DIAMOND",
    "CHERRY",
    "BERMUDA",
    "CIRCLE",
    "BALL",
    "BRUSH",
    "MUMMY",
    "THIEF",
    "THUMB",
    "UNDERTAKER",
    "BRIDGE",
    "CHURCH",
    "NURSE",
    "BEAT",
    "SKUNK",
    "JOCKEY",
    "JUNK",
    "BOLT",
    "BACK",
    "COMPOUND",
    "COMIC",
    "CHECK",
    "VENUS",
    "FEVER",
  ],
  11: [
    "SPRING",
    "KNEE",
    "HAM",
    "SATELLITE",
    "TURTLE",
    "WISH",
    "POLE",
    "SCALE",
    "TELESCOPE",
    "TEACHER",
    "OIL",
    "SALAD",
    "WAKE",
    "BRIDE",
    "NUT",
    "ATLANTIS",
    "TIP",
    "TAIL",
    "NAIL",
    "BEE",
    "DAY",
    "BISCUIT",
    "PAD",
    "FIRE",
  ],
  12: [
    "LIMOUSINE",
    "KID",
    "LEMON",
    "POWDER",
    "CAMEL",
    "MAIL",
    "KING",
    "TENT",
    "WINE",
    "SHERWOOD",
    "TABOO",
    "WET",
    "INDIA",
    "VEIN",
    "MARCH",
    "IRON",
    "BICYCLE",
    "SOLO",
    "HOT",
    "LOCK",
    "LOCH NESS",
    "PEA",
    "JUPITER",
  ],
  13: [
    "BANANA",
    "DEATH",
    "SUN",
    "PADDLE",
    "COLD",
    "AMAZON",
    "APPLICATION",
    "DRAG",
    "FRANCE",
    "SUIT",
    "DICE",
    "CAMP",
    "TAG",
    "CONCERT",
    "BATH",
    "BUTTERFLY",
    "BLACKSMITH",
    "FRANKENSTEIN",
    "WAR",
    "CAPITAL",
    "PENTAGON",
    "BOTTLE",
    "EGYPT",
    "STAMP",
    "ANGEL",
  ],
  14: [
    "MICROSCOPE",
    "MOSCOW",
    "LASER",
    "TURN",
    "COLUMBUS",
    "BEAM",
    "SPOT",
    "DEGREE",
    "BOMB",
    "POISON",
    "DOLLAR",
    "MINE",
    "PLOT",
    "PASS",
    "SCORPION",
    "SHOP",
    "PUMPKIN",
    "JET",
    "JAM",
    "NAVAL",
    "CANE",
    "HORSE",
    "OIL",
    "NURSE",
  ],
  15: [
    "GIRL",
    "MODE",
    "ROOKIE",
    "GERBIL",
    "SEED",
    "CALENDAR",
    "SWEAT",
    "LACE",
    "SHARE",
    "ONION",
    "CLOUD",
    "MONKEY",
    "SALT",
    "STAG",
    "ARTIST",
    "PAINTING",
    "FANG",
    "STONEHENGE",
    "ICE",
    "POLE",
    "PINK",
    "SPINE",
    "DRIVER",
    "PILLOW",
    "MUSKETEER",
  ],
  16: [
    "BERLIN",
    "KNIFE",
    "SHOP",
    "ATLANTIS",
    "ROOT",
    "EGYPT",
    "FANG",
    "IVORY",
    "BELL",
    "BOX",
    "POUND",
    "PISTOL",
    "MASS",
    "PLASTIC",
    "PEPPER",
    "HOLLYWOOD",
    "CHEST",
    "SCORPION",
    "FIDDLE",
    "BOOT",
    "IRON",
    "EYE",
    "OLIVE",
  ],
  17: [
    "COMPUTER",
    "ARM",
    "SQUARE",
    "SHED",
    "STAR",
    "SPOT",
    "EYE",
    "PROCESSOR",
    "BOLT",
    "ANGEL",
    "CYCLE",
    "BEIJING",
    "PILOT",
    "AUSTRALIA",
    "SHOT",
    "ROW",
    "FALL",
    "SKI",
    "AIR",
    "FISH",
    "BAR",
    "PIRATE",
    "SERVER",
    "DUCK",
    "SKYSCRAPER",
  ],
  18: [
    "MATTRESS",
    "LOOSE",
    "SAFE",
    "RAGE",
    "FARM",
    "STEAM",
    "CRICKET",
    "RED",
    "POKER",
    "PILOT",
    "GENIE",
    "HEART",
    "HERCULES",
    "COUNTRY",
    "COVER",
    "DELTA",
    "REVOLUTION",
    "BOTTOM",
    "FLUFF",
    "MEXICO",
    "BLACK",
    "IVORY",
    "WILD",
    "ANIMAL",
  ],
  19: [
    "TATTOO",
    "APPLE",
    "OLYMPUS",
    "STRAW",
    "SOUL",
    "MIRROR",
    "CRYSTAL",
    "GREECE",
    "MARACAS",
    "EMBASSY",
    "STAR",
    "CRAB",
    "STEAM",
    "AZTEC",
    "VEGAS",
    "TRICK",
    "WATER",
    "AXE",
    "KEY",
    "BUCK",
    "LAWYER",
    "BOXER",
    "PENGUIN",
    "ROBOT",
  ],
  20: [
    "DRESS",
    "KNOB",
    "THROAT",
    "FLUFF",
    "BETA",
    "GANG",
    "GROUP",
    "EAT",
    "MOTEL",
    "COCKTAIL",
    "SHED",
    "GRANDMA",
    "CINDERELLA",
    "CHEEK",
    "RACK",
    "SHIPYARD",
    "PRICK",
    "BREAK",
    "BOMB",
    "BONSAI",
    "EMISSION",
    "CANDLE",
    "SWEAT",
    "LOTION",
    "DRONE",
  ],
};

export { WORD_SETS, RANDOM_WORDS };
